# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f96581f7070f5dcf55dd67e26b2ca5096bb9bcd5bc1a222c5955eb30b346df7ecf31d8df8fa6f128fc6712e08af1a65fff1afac072bcdbd84d48c33c36be955

test:
  secret_key_base: 5fc7e1bb51721f70deb979c24dafbebc847933365dfd81cd79f6e6233101e59f001f1dff9f30a8e28d503bd46e5538a37153a5566b25d5f6c495220dc394f068

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
